title: "elliot charney"
description: ""
about: "full stack software engineer"
location: "san francisco"
email: "elliot.charney@protonmail.com"
baseurl: ""
url: ""
twitter_username:
github_username:  shonin
show_about_link:
linkedin_url: https://www.linkedin.com/in/elliotcharney/

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "About Me"
imprint_btn: "About"
name_badge: "a post by"
# rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
